// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniChat.Infrastructure.Persistence;

#nullable disable

namespace OmniChat.Infrastructure.Migrations
{
    [DbContext(typeof(OmniChatDbContext))]
    [Migration("20260427151746_InvoiceCode")]
    partial class InvoiceCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("BatchCodeSeq");

            modelBuilder.HasSequence("InvoiceCodeSeq")
                .StartsAt(100000L);

            modelBuilder.HasSequence<int>("KeywordCodeSeq");

            modelBuilder.HasSequence<int>("OrderCodeSeq");

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<bool>("IsFirstLogined")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Allocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AllocationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("WalletId");

                    b.ToTable("Allocations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.BatchAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ActionById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NewValue")
                        .HasColumnType("integer");

                    b.Property<int>("OldValue")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProductBatchId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionById");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("BatchAudits");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ChatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChatTemplates");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClaimTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SubmitDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClaimTypeId");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupportConversationId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ClaimType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClaimTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationWarning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsReviewed")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("WarningType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("ConversationId", "WarningType");

                    b.ToTable("ConversationWarnings");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CreditNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreditNoteStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreditNoteType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("CreditNotes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<bool>("KeywordActive")
                        .HasColumnType("boolean");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ConversationId", "IsRead");

                    b.HasIndex("ConversationId", "Timestamp");

                    b.ToTable("CustomerMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<double>("DebtLimit")
                        .HasColumnType("double precision");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FacebookSenderId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramSenderId")
                        .HasColumnType("text");

                    b.Property<bool>("IsFormSent")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsNewCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<bool>("IsProfileCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ZaloSenderId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FacebookOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderId");

                    b.ToTable("FacebookOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FeedBack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupportConversationId")
                        .IsUnique();

                    b.HasIndex("StaffId", "Rating");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InstagramOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime?>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderId");

                    b.ToTable("InstagramOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.IntentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IntentTypePiority")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TypeName");

                    b.ToTable("IntentTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<double>("DeductedAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("EndedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("InvoiceCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValueSql("nextval('\"InvoiceCodeSeq\"')");

                    b.Property<string>("InvoiceMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InvoiceStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<double>("PaidAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("InvoiceCode")
                        .IsUnique();

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("'KW' || LPAD(nextval('\"KeywordCodeSeq\"')::text, 6, '0')");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("IntentTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<string>("KeywordText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IntentTypeId");

                    b.HasIndex("KeywordText");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageIntentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("IntentTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IntentTypeId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageIntentTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("ConversationId", "IsRead");

                    b.HasIndex("StaffId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("'OD' || LPAD(nextval('\"OrderCodeSeq\"')::text, 6, '0')");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeliveriedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryStatus")
                        .HasColumnType("text");

                    b.Property<Guid?>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatorId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("DriverId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.PostSaleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PostSaleRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .IsUnique();

                    b.HasIndex("PostSaleRequestId");

                    b.ToTable("PostSaleItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.PostSaleRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("FraudFlag")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PresentByStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("RefundAmount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("RequestedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ResolveById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PresentByStaffId");

                    b.HasIndex("ResolveById");

                    b.ToTable("PostSaleRequests");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<int>("LifeSpan")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductPackagingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("VolumeMl")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products", t =>
                        {
                            t.HasCheckConstraint("CK_Product_Price_Min", "\"Price\" >= 0");

                            t.HasCheckConstraint("CK_Product_Quantity_Min", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ProductBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValueSql("'LOT' || LPAD(nextval('\"BatchCodeSeq\"')::text, 6, '0')");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<bool?>("IsExpired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<DateTime?>("ManuFactureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.ToTable("ProductBatches", t =>
                        {
                            t.HasCheckConstraint("CK_ProductBatch_Quantity_Min", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueIdentity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffIntentType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("IntentTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("IntentTypeId", "StaffId");

                    b.ToTable("StaffIntentTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double?>("AvgFirstResponseTime")
                        .HasColumnType("double precision");

                    b.Property<double?>("AvgTaskHandleTime")
                        .HasColumnType("double precision");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("integer");

                    b.Property<int>("ConversationOwned")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FromTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReassignmentCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskCompleted")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ToTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalFirstResponseTime")
                        .HasColumnType("integer");

                    b.Property<int>("TotalTaskHandleTime")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.ToTable("StaffPerformances");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActiveCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CloseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FirstResponseAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastCustomerMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastStaffMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProvidersId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("ReminderSent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCustomerId");

                    b.HasIndex("ProvidersId");

                    b.HasIndex("ActiveCustomerId", "ProvidersId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("ActiveStaffId", "Status");

                    b.HasIndex("ProvidersId", "Status");

                    b.ToTable("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationFileId");

                    b.HasIndex("SupportConversationId", "ConversationFileId")
                        .IsUnique();

                    b.ToTable("SupportConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportStaffMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "Status");

                    b.HasIndex("SupportConversationId", "Status");

                    b.ToTable("SupportStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("CompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentAssignedStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IntentTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.Property<int>("TaskPiority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssignedStaffId");

                    b.HasIndex("IntentTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("SupportConversationId");

                    b.ToTable("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.TaskAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ActionById")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActionToId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionById");

                    b.HasIndex("ActionToId");

                    b.HasIndex("SupportTaskId");

                    b.ToTable("TaskActions");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.TaskCancelReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CancelledByStaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReasonType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupportTaskId");

                    b.ToTable("TaskCancelReasons");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ZaloOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime?>("LastRefreshTokenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderId");

                    b.ToTable("ZaloOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Allocation", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Invoice", "Invoice")
                        .WithMany("Allocations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Wallet", "Wallet")
                        .WithMany("Allocations")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.BatchAudit", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "ActionBy")
                        .WithMany()
                        .HasForeignKey("ActionById");

                    b.HasOne("OmniChat.Infrastructure.Models.ProductBatch", "ProductBatch")
                        .WithMany("BatchAudits")
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionBy");

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Claim", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ClaimType", "ClaimType")
                        .WithMany("Claims")
                        .HasForeignKey("ClaimTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Claims")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("Claims")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClaimType");

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationWarning", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "Conversation")
                        .WithMany("ConversationWarnings")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("ConversationWarnings")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CreditNote", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Invoice", "Invoice")
                        .WithMany("CreditNotes")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.Order", "Order")
                        .WithMany("CreditNotes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "Conversation")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FacebookOathToken", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Provider")
                        .WithMany("FacebookOathTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FeedBack", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("FeedBacks")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithOne("FeedBack")
                        .HasForeignKey("OmniChat.Infrastructure.Models.FeedBack", "SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InstagramOathToken", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Provider")
                        .WithMany("InstagramOathTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Invoice", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.IntentType", "IntentType")
                        .WithMany("Keywords")
                        .HasForeignKey("IntentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntentType");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageIntentType", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.IntentType", "IntentType")
                        .WithMany("MessageIntentTypes")
                        .HasForeignKey("IntentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.CustomerMessage", "CustomerMessage")
                        .WithMany("MessageIntentTypes")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerMessage");

                    b.Navigation("IntentType");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Notification", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("Notifications")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Notifications")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Order", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Creator")
                        .WithMany("OrdersCreated")
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Driver")
                        .WithMany("OrdersAsDriver")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.Invoice", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Creator");

                    b.Navigation("CustomerProfile");

                    b.Navigation("Driver");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.OrderItem", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.ProductBatch", "ProductBatch")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.PostSaleItem", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.OrderItem", "OrderItem")
                        .WithOne("PostSaleItem")
                        .HasForeignKey("OmniChat.Infrastructure.Models.PostSaleItem", "OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.PostSaleRequest", "PostSaleRequest")
                        .WithMany("PostSaleItems")
                        .HasForeignKey("PostSaleRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderItem");

                    b.Navigation("PostSaleRequest");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.PostSaleRequest", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "Customer")
                        .WithMany("PostSaleRequests")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Order", "Order")
                        .WithMany("PostSaleRequests")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "PresentByStaff")
                        .WithMany("PostSaleRequestsPresented")
                        .HasForeignKey("PresentByStaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "ResolveBy")
                        .WithMany("PostSaleRequestsResolved")
                        .HasForeignKey("ResolveById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("PresentByStaff");

                    b.Navigation("ResolveBy");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Product", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ProductBatch", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.RefreshToken", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Account", "Account")
                        .WithOne("Staff")
                        .HasForeignKey("OmniChat.Infrastructure.Models.Staff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffIntentType", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.IntentType", "IntentType")
                        .WithMany("StaffIntentTypes")
                        .HasForeignKey("IntentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("StaffIntentTypes")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IntentType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffPerformance", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("StaffPerformances")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ActiveCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ActiveStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Providers")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerProfile");

                    b.Navigation("Providers");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversationFile", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ConversationFile", "ConversationFile")
                        .WithMany("SupportConversationFiles")
                        .HasForeignKey("ConversationFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportConversationFiles")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationFile");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportStaffMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("SupportStaffMessages")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportStaffMessages")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportTask", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "CurrentAssignedStaff")
                        .WithMany("SupportTasks")
                        .HasForeignKey("CurrentAssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.IntentType", "IntentType")
                        .WithMany("SupportTasks")
                        .HasForeignKey("IntentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportTasks")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentAssignedStaff");

                    b.Navigation("IntentType");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.TaskAction", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "ActionBy")
                        .WithMany("ActionsPerformed")
                        .HasForeignKey("ActionById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "ActionTo")
                        .WithMany("ActionsReceived")
                        .HasForeignKey("ActionToId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.SupportTask", "SupportTask")
                        .WithMany("TaskActions")
                        .HasForeignKey("SupportTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionBy");

                    b.Navigation("ActionTo");

                    b.Navigation("SupportTask");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.TaskCancelReason", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportTask", "SupportTask")
                        .WithMany("TaskCancelReasons")
                        .HasForeignKey("SupportTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportTask");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Transaction", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Wallet", "Wallet")
                        .WithMany("Transactions")
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Wallet", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithOne("Wallet")
                        .HasForeignKey("OmniChat.Infrastructure.Models.Wallet", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ZaloOathToken", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Provider")
                        .WithMany("ZaloOathTokens")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Staff")
                        .IsRequired();
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ClaimType", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationFile", b =>
                {
                    b.Navigation("SupportConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.Navigation("MessageIntentTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.Navigation("CustomerMessages");

                    b.Navigation("Invoices");

                    b.Navigation("Orders");

                    b.Navigation("PostSaleRequests");

                    b.Navigation("SupportConversations");

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.IntentType", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("MessageIntentTypes");

                    b.Navigation("StaffIntentTypes");

                    b.Navigation("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Invoice", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("CreditNotes");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Order", b =>
                {
                    b.Navigation("CreditNotes");

                    b.Navigation("OrderItems");

                    b.Navigation("PostSaleRequests");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.OrderItem", b =>
                {
                    b.Navigation("PostSaleItem");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.PostSaleRequest", b =>
                {
                    b.Navigation("PostSaleItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Product", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ProductBatch", b =>
                {
                    b.Navigation("BatchAudits");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Provider", b =>
                {
                    b.Navigation("FacebookOathTokens");

                    b.Navigation("InstagramOathTokens");

                    b.Navigation("SupportConversations");

                    b.Navigation("ZaloOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.Navigation("ActionsPerformed");

                    b.Navigation("ActionsReceived");

                    b.Navigation("Claims");

                    b.Navigation("ConversationWarnings");

                    b.Navigation("FeedBacks");

                    b.Navigation("Notifications");

                    b.Navigation("OrdersAsDriver");

                    b.Navigation("OrdersCreated");

                    b.Navigation("PostSaleRequestsPresented");

                    b.Navigation("PostSaleRequestsResolved");

                    b.Navigation("StaffIntentTypes");

                    b.Navigation("StaffPerformances");

                    b.Navigation("SupportConversations");

                    b.Navigation("SupportStaffMessages");

                    b.Navigation("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("ConversationWarnings");

                    b.Navigation("CustomerMessages");

                    b.Navigation("FeedBack")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("SupportConversationFiles");

                    b.Navigation("SupportStaffMessages");

                    b.Navigation("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportTask", b =>
                {
                    b.Navigation("TaskActions");

                    b.Navigation("TaskCancelReasons");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Wallet", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
