// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniChat.Infrastructure.Persistence;

#nullable disable

namespace OmniChat.Infrastructure.Migrations
{
    [DbContext(typeof(OmniChatDbContext))]
    [Migration("20260225062621_RemoveRelationShipBetweenClaimKeywordType")]
    partial class RemoveRelationShipBetweenClaimKeywordType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<bool>("IsFirstLogined")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.BillingItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<string>("BillStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PaymentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentId");

                    b.ToTable("BillingItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ChatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChatTemplates");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClaimTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClaimTypeId");

                    b.HasIndex("StaffId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ClaimType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClaimTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("KeywordActive")
                        .HasColumnType("boolean");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ConversationId", "Timestamp");

                    b.ToTable("CustomerMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("CreateDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FacebookSenderId")
                        .HasColumnType("text");

                    b.Property<string>("InstagramSenderId")
                        .HasColumnType("text");

                    b.Property<bool?>("IsNewCustomer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ZaloSenderId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FacebookOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("FacebookOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FeedBack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupportConversationId")
                        .IsUnique();

                    b.HasIndex("StaffId", "Rating");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InstagramOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("LastUpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("InstagramOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InternalConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConversationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InternalConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InternalConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("InternalConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationFileId");

                    b.HasIndex("InternalConversationId");

                    b.ToTable("InternalConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InternalStaffMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("InternalConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("InternalConversationId");

                    b.HasIndex("StaffId");

                    b.ToTable("InternalStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<Guid>("KeyWordTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("KeywordText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Piority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("KeyWordTypeId");

                    b.HasIndex("KeywordText");

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.KeywordTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TypeName");

                    b.ToTable("KeywordTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("EndedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageKeywordTypesId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("KeywordId");

                    b.HasIndex("MessageKeywordTypesId");

                    b.ToTable("MessageKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeywordTypes", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("KeywordTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("KeywordTypeId");

                    b.HasIndex("MessageId");

                    b.ToTable("MessageKeywordTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("ConversationId", "IsRead");

                    b.HasIndex("StaffId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeliveryStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalAmount")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("Status");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProductBatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductBatchId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Total")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<int>("LifeSpan")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductPackagingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<double>("VolumeMl")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ProductBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("ManuFactureDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductBatches");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<Guid?>("KeyWordTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("KeyWordTypeId");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActiveCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProvidersId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCustomerId");

                    b.HasIndex("ProvidersId");

                    b.HasIndex("ActiveCustomerId", "ProvidersId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Pending'");

                    b.HasIndex("ActiveStaffId", "Status");

                    b.HasIndex("ProvidersId", "Status");

                    b.ToTable("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationFileId");

                    b.HasIndex("SupportConversationId", "ConversationFileId")
                        .IsUnique();

                    b.ToTable("SupportConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportStaffMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "Status");

                    b.HasIndex("SupportConversationId", "Status");

                    b.ToTable("SupportStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CompleteDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CurrentAssignedStaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CurrentAssignedStaffId");

                    b.HasIndex("KeywordTypeId");

                    b.HasIndex("Status");

                    b.HasIndex("SupportConversationId");

                    b.ToTable("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.TaskAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportTaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SupportTaskId");

                    b.ToTable("TaskAssignmentHistories");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ZaloOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime>("LastRefreshTokenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ZaloOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.BillingItem", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Order", "Order")
                        .WithMany("BillingItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Payment", "Payment")
                        .WithMany("BillingItems")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Order");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Claim", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ClaimType", "ClaimType")
                        .WithMany("Claims")
                        .HasForeignKey("ClaimTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Claims")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimType");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "Conversation")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FeedBack", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("FeedBacks")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithOne("FeedBack")
                        .HasForeignKey("OmniChat.Infrastructure.Models.FeedBack", "SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InternalConversationFile", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ConversationFile", "ConversationFile")
                        .WithMany("InternalConversationFiles")
                        .HasForeignKey("ConversationFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.InternalConversation", "InternalConversation")
                        .WithMany("InternalConversationFiles")
                        .HasForeignKey("InternalConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationFile");

                    b.Navigation("InternalConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InternalStaffMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.InternalConversation", "InternalConversation")
                        .WithMany("InternalMessages")
                        .HasForeignKey("InternalConversationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("InternalStaffMessages")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InternalConversation");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.KeywordTypes", "KeyWordType")
                        .WithMany("Keywords")
                        .HasForeignKey("KeyWordTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KeyWordType");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeyword", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Keyword", "Keyword")
                        .WithMany("MessageKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.MessageKeywordTypes", "MessageKeywordTypes")
                        .WithMany("MessageKeywords")
                        .HasForeignKey("MessageKeywordTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Keyword");

                    b.Navigation("MessageKeywordTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeywordTypes", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.KeywordTypes", "KeywordTypes")
                        .WithMany("MessageKeywordTypes")
                        .HasForeignKey("KeywordTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.CustomerMessage", "CustomerMessage")
                        .WithMany("MessageKeywordTypes")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerMessage");

                    b.Navigation("KeywordTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Notification", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("Notifications")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Notifications")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Order", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.OrderItem", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.ProductBatch", "ProductBatch")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("ProductBatch");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Payment", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("Payments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerProfile");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ProductBatch", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Product", "Product")
                        .WithMany("ProductBatches")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.RefreshToken", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Account", "Account")
                        .WithOne("Staff")
                        .HasForeignKey("OmniChat.Infrastructure.Models.Staff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OmniChat.Infrastructure.Models.KeywordTypes", "KeywordTypes")
                        .WithMany("Staffs")
                        .HasForeignKey("KeyWordTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("KeywordTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ActiveCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ActiveStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Providers")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerProfile");

                    b.Navigation("Providers");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversationFile", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ConversationFile", "ConversationFile")
                        .WithMany("SupportConversationFiles")
                        .HasForeignKey("ConversationFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportConversationFiles")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationFile");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportStaffMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("SupportStaffMessages")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportStaffMessages")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportTask", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "CurrentAssignedStaff")
                        .WithMany("SupportTasks")
                        .HasForeignKey("CurrentAssignedStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.KeywordTypes", "KeywordType")
                        .WithMany("SupportTasks")
                        .HasForeignKey("KeywordTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportTasks")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentAssignedStaff");

                    b.Navigation("KeywordType");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.TaskAssignmentHistory", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportTask", "SupportTask")
                        .WithMany("TaskAssignmentHistories")
                        .HasForeignKey("SupportTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SupportTask");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Staff")
                        .IsRequired();
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ClaimType", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationFile", b =>
                {
                    b.Navigation("InternalConversationFiles");

                    b.Navigation("SupportConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.Navigation("MessageKeywordTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.Navigation("CustomerMessages");

                    b.Navigation("Orders");

                    b.Navigation("Payments");

                    b.Navigation("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.InternalConversation", b =>
                {
                    b.Navigation("InternalConversationFiles");

                    b.Navigation("InternalMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.Navigation("MessageKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.KeywordTypes", b =>
                {
                    b.Navigation("Keywords");

                    b.Navigation("MessageKeywordTypes");

                    b.Navigation("Staffs");

                    b.Navigation("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeywordTypes", b =>
                {
                    b.Navigation("MessageKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Order", b =>
                {
                    b.Navigation("BillingItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Payment", b =>
                {
                    b.Navigation("BillingItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Product", b =>
                {
                    b.Navigation("ProductBatches");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ProductBatch", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Provider", b =>
                {
                    b.Navigation("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("FeedBacks");

                    b.Navigation("InternalStaffMessages");

                    b.Navigation("Notifications");

                    b.Navigation("SupportConversations");

                    b.Navigation("SupportStaffMessages");

                    b.Navigation("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.Navigation("CustomerMessages");

                    b.Navigation("FeedBack")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("SupportConversationFiles");

                    b.Navigation("SupportStaffMessages");

                    b.Navigation("SupportTasks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportTask", b =>
                {
                    b.Navigation("TaskAssignmentHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
