// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmniChat.Infrastructure.Persistence;

#nullable disable

namespace OmniChat.Infrastructure.Migrations
{
    [DbContext(typeof(OmniChatDbContext))]
    [Migration("20260119162210_nullAbleActiveStaffId")]
    partial class nullAbleActiveStaffId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<bool>("IsFirstLogined")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NewData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("OldData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreateDate");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ChatTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ChatTemplates");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Claim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ClaimTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmitDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClaimTypeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("StaffId");

                    b.ToTable("Claims");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ClaimType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ClaimTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<bool>("KeywordActive")
                        .HasColumnType("boolean");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ConversationId", "Timestamp");

                    b.ToTable("CustomerMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProvidersId")
                        .HasColumnType("uuid");

                    b.Property<string>("SenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProvidersId");

                    b.ToTable("CustomerProfiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ConversationName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentConversationTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentConversationTypeId");

                    b.HasIndex("DepartmentId", "DepartmentConversationTypeId", "Status");

                    b.ToTable("DepartmentConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationFileId");

                    b.HasIndex("DepartmentConversationId", "ConversationFileId")
                        .IsUnique();

                    b.ToTable("DepartmentConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversationType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DepartmentConversationTypes");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("KeywordId")
                        .IsUnique();

                    b.ToTable("DepartmentKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentStaffMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DepartmentConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("DepartmentConversationId", "Status");

                    b.ToTable("DepartmentStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FeedBack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("SupportConversationId")
                        .IsUnique();

                    b.HasIndex("StaffId", "Rating");

                    b.ToTable("FeedBacks");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Inquiry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AssignedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SupportConversationId")
                        .IsUnique();

                    b.HasIndex("DepartmentId", "Status");

                    b.HasIndex("StaffId", "Status");

                    b.HasIndex("SupportConversationId", "IsActive")
                        .IsUnique();

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<string>("KeywordText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Piority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Keywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Kpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AchivedValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("false");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Kpis");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("CustomerMessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KeywordId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerMessageId");

                    b.HasIndex("KeywordId");

                    b.HasIndex("KeywordId", "CustomerMessageId")
                        .IsUnique();

                    b.ToTable("MessageKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("StaffId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StaffId");

                    b.HasIndex("ConversationId", "IsRead");

                    b.HasIndex("StaffId", "IsRead");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("RefeshTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValueSql("true");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id");

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Staffs");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffKpi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("CurrentValue")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KpiId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KpiId", "Status");

                    b.HasIndex("StaffId", "KpiId")
                        .IsUnique();

                    b.HasIndex("StaffId", "Status");

                    b.ToTable("StaffKpis");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("ShiftId", "Status");

                    b.HasIndex("StaffId", "ShiftId")
                        .IsUnique();

                    b.ToTable("StaffShifts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ActiveCustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActiveStaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvartarUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDistributed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProvidersId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveCustomerId");

                    b.HasIndex("ActiveStaffId", "Status");

                    b.HasIndex("ProvidersId", "Status");

                    b.ToTable("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversationFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ConversationFileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationFileId");

                    b.HasIndex("SupportConversationId", "ConversationFileId")
                        .IsUnique();

                    b.ToTable("SupportConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportStaffMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("StaffId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SupportConversationId")
                        .HasColumnType("uuid");

                    b.Property<long>("Timestamp")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StaffId", "Status");

                    b.HasIndex("SupportConversationId", "Status");

                    b.ToTable("SupportStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ZaloOathToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("AccessTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastRefreshTokenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenExpiredDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.ToTable("ZaloOathTokens");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Claim", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ClaimType", "ClaimType")
                        .WithMany("Claims")
                        .HasForeignKey("ClaimTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("Claims")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Claims")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClaimType");

                    b.Navigation("Department");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "Conversation")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "Customer")
                        .WithMany("CustomerMessages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Providers")
                        .WithMany("CustomerProfiles")
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Providers");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversation", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.DepartmentConversationType", "DepartmentConversationType")
                        .WithMany("DepartmentConversations")
                        .HasForeignKey("DepartmentConversationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("DepartmentConversations")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("DepartmentConversationType");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversationFile", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ConversationFile", "ConversationFile")
                        .WithMany("DepartmentConversationFiles")
                        .HasForeignKey("ConversationFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.DepartmentConversation", "DepartmentConversation")
                        .WithMany("DepartmentConversationFiles")
                        .HasForeignKey("DepartmentConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationFile");

                    b.Navigation("DepartmentConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentKeyword", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("DepartmentKeywords")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Keyword", "Keyword")
                        .WithOne("DepartmentKeyword")
                        .HasForeignKey("OmniChat.Infrastructure.Models.DepartmentKeyword", "KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentStaffMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.DepartmentConversation", "DepartmentConversation")
                        .WithMany("DepartmentStaffMessages")
                        .HasForeignKey("DepartmentConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("DepartmentStaffMessages")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentConversation");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.FeedBack", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("FeedBacks")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithOne("FeedBack")
                        .HasForeignKey("OmniChat.Infrastructure.Models.FeedBack", "SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Inquiry", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("Inquiries")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Inquiries")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithOne("Inquiry")
                        .HasForeignKey("OmniChat.Infrastructure.Models.Inquiry", "SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Kpi", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("Kpis")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.MessageKeyword", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerMessage", "CustomerMessage")
                        .WithMany("MessageKeywords")
                        .HasForeignKey("CustomerMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Keyword", "Keyword")
                        .WithMany("MessageKeywords")
                        .HasForeignKey("KeywordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CustomerMessage");

                    b.Navigation("Keyword");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Notification", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("Notifications")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("Notifications")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.RefreshToken", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Account", "Account")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Shift", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("Shifts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Account", "Account")
                        .WithOne("Staff")
                        .HasForeignKey("OmniChat.Infrastructure.Models.Staff", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OmniChat.Infrastructure.Models.Department", "Department")
                        .WithMany("Staffs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffKpi", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Kpi", "Kpi")
                        .WithMany("StaffKpis")
                        .HasForeignKey("KpiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("StaffKpis")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kpi");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.StaffShift", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Shift", "Shift")
                        .WithMany("StaffShifts")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("StaffShifts")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.CustomerProfile", "CustomerProfile")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ActiveCustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ActiveStaffId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OmniChat.Infrastructure.Models.Provider", "Providers")
                        .WithMany("SupportConversations")
                        .HasForeignKey("ProvidersId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerProfile");

                    b.Navigation("Providers");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversationFile", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.ConversationFile", "ConversationFile")
                        .WithMany("SupportConversationFiles")
                        .HasForeignKey("ConversationFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportConversationFiles")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConversationFile");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportStaffMessage", b =>
                {
                    b.HasOne("OmniChat.Infrastructure.Models.Staff", "Staff")
                        .WithMany("SupportStaffMessages")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OmniChat.Infrastructure.Models.SupportConversation", "SupportConversation")
                        .WithMany("SupportStaffMessages")
                        .HasForeignKey("SupportConversationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SupportConversation");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Account", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("Staff")
                        .IsRequired();
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ClaimType", b =>
                {
                    b.Navigation("Claims");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.ConversationFile", b =>
                {
                    b.Navigation("DepartmentConversationFiles");

                    b.Navigation("SupportConversationFiles");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerMessage", b =>
                {
                    b.Navigation("MessageKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.CustomerProfile", b =>
                {
                    b.Navigation("CustomerMessages");

                    b.Navigation("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Department", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("DepartmentConversations");

                    b.Navigation("DepartmentKeywords");

                    b.Navigation("Inquiries");

                    b.Navigation("Kpis");

                    b.Navigation("Shifts");

                    b.Navigation("Staffs");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversation", b =>
                {
                    b.Navigation("DepartmentConversationFiles");

                    b.Navigation("DepartmentStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.DepartmentConversationType", b =>
                {
                    b.Navigation("DepartmentConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Keyword", b =>
                {
                    b.Navigation("DepartmentKeyword")
                        .IsRequired();

                    b.Navigation("MessageKeywords");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Kpi", b =>
                {
                    b.Navigation("StaffKpis");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Provider", b =>
                {
                    b.Navigation("CustomerProfiles");

                    b.Navigation("SupportConversations");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Shift", b =>
                {
                    b.Navigation("StaffShifts");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.Staff", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("DepartmentStaffMessages");

                    b.Navigation("FeedBacks");

                    b.Navigation("Inquiries");

                    b.Navigation("Notifications");

                    b.Navigation("StaffKpis");

                    b.Navigation("StaffShifts");

                    b.Navigation("SupportConversations");

                    b.Navigation("SupportStaffMessages");
                });

            modelBuilder.Entity("OmniChat.Infrastructure.Models.SupportConversation", b =>
                {
                    b.Navigation("CustomerMessages");

                    b.Navigation("FeedBack")
                        .IsRequired();

                    b.Navigation("Inquiry")
                        .IsRequired();

                    b.Navigation("Notifications");

                    b.Navigation("SupportConversationFiles");

                    b.Navigation("SupportStaffMessages");
                });
#pragma warning restore 612, 618
        }
    }
}
