services:
    backend:
        image: khoanam/omnichat:V2
        container_name: omnichat-backend
        ports:
            - "5000:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - REDIS=redis:6379
        depends_on:
            redis:
                condition: service_healthy
        restart: always

    redis:
        image: redis:7
        container_name: omnichat-redis
        ports:
            - "6379:6379"
        healthcheck:
            test: [ "CMD", "redis-cli", "ping" ]
            interval: 5s
            timeout: 3s
            retries: 5
        restart: always
